
moveStylesDictionary = {
    "Acid Armor": 1,
    "Conversion 2": 1,
    "Harden": 1,
    "Tail Glow": 1,
    "Agility": 1,
    "Cosmic Power": 1,
    "Howl": 1,
    "Withdraw": 1,
    "Amnesia": 1,
    "Defense Curl": 1,
    "Iron Defense": 1,
    "Belly Drum": 1,
    "Dragon Dance": 1,
    "Minimize": 1,
    "Barrier": 1,
    "Double Team": 1,
    "Meditate": 1,
    "Bulk Up": 1,
    "Focus Energy": 1,
    "Psych Up": 1,
    "Calm Mind": 1,
    "Growth": 1,
    "Sharpen": 1,
    "Charge": 1,
    "Snatch": 1,
    "Conversion": 1,
    "Swords Dance": 1,
    "Attract": 2,
    "Leech Seed": 2,
    "Spider Web": 2,
    "Thunder Wave": 2,
    "Glare": 2,
    "Sleep Powder": 2,
    "Sweet Kiss": 2,
    "Flatter": 2,
    "Sing": 2,
    "Swagger": 2,
    "Block": 2,
    "Lovely Kiss": 2,
    "Spikes": 2,
    "Torment": 2,
    "Confuse Ray": 2,
    "Mean Look": 2,
    "Spore": 2,
    "Toxic": 2,
    "Disable": 2,
    "Poison Gas": 2,
    "Stun Spore": 2,
    "Yawn": 2,
    "Encore": 2,
    "PoisonPowder": 2,
    "Supersonic": 2,
    "Will-O-Wisp": 2,
    "GrassWhistle": 2,
    "Snatch": 2,
    "Taunt": 2,
    "Hypnosis": 2,
    "Imprison": 2,
    "Teeter Dance": 2,
    "Aromatherapy": 3,
    "Milk Drink": 3,
    "Slack Off": 3,
    "Baton Pass": 3,
    "Mist": 3,
    "Softboiled": 3,
    "Detect": 3,
    "Moonlight": 3,
    "Swallow": 3,
    "Endure": 3,
    "Morning Sun": 3,
    "Synthesis": 3,
    "Haze": 3,
    "Mud Sport": 3,
    "Recycle": 3,
    "Heal Bell": 3,
    "Protect": 3,
    "Refresh": 3,
    "Ingrain": 3,
    "Recover": 3,
    "Water Sport": 3,
    "Light Screen": 3,
    "Reflect": 3,
    "Wish": 3,
    "Magic Coat": 3,
    "Rest": 3,
    "Safeguard": 3,
    "Bide": 4,
    "Focus Punch": 4,
    "Mirror Coat": 4,
    "Volt Tackle": 4,
    "Blast Burn": 4,
    "Frenzy Plant": 4,
    "Overheat": 4,
    "Counter": 4,
    "Grudge": 4,
    "Pain Split": 4,
    "Destiny Bond": 4,
    "Guillotine": 4,
    "Perish Song": 4,
    "Double-Edge": 4,
    "Horn Drill": 4,
    "Psycho Boost": 4,
    "Explosion": 4,
    "Hydro Cannon": 4,
    "Reversal": 4,
    "Facade": 4,
    "Hyper Beam": 4,
    "Selfdestruct": 4,
    "Fissure": 4,
    "Memento": 4,
    "Sky Attack": 4,
    "Flail": 4,
    "Charm": 5,
    "Metal Sound": 5,
    "Tail Whip": 5,
    "Cotton Spore": 5,
    "Sand-Attack": 5,
    "Tickle": 5,
    "Fake Tears": 5,
    "Scary Face": 5,
    "FeatherDance": 5,
    "Screech": 5,
    "Flash": 5,
    "SmokeScreen": 5,
    "Growl": 5,
    "Spite": 5,
    "Kinesis": 5,
    "String Shot": 5,
    "Knock Off": 5,
    "Sweet Scent": 5,
    "Leer": 5,
    "Assist": 6,
    "Sketch": 6,
    "Camouflage": 6,
    "Skill Swap": 6,
    "Curse": 6,
    "Substitute": 6,
    "Follow Me": 6,
    "Transform": 6,
    "Metronome": 6,
    "Trick": 6,
    "Mimic": 6,
    "Mirror Move": 6,
    "Present": 6,
    "Role Play": 6,
    "Hail": 7,
    "Rain Dance": 7,
    "Sandstorm": 7,
    "Sunny Day": 7,
    "Weather Ball": 7
}


battleStylesDictionary = {
    "None": "appears to be free-spirited and unrestrained",
    1: "appears to be one based on total preparation",
    2: "appears to be slow and steady",
    3: "appears to be one of endurance",
    4: "appears to be high risk, high return",
    5: "appears to be weakening the foe to start",
    6: "appears to be impossible to predict",
    7: "appears to depend on the battle's flow",
    "flexible": "appears to be flexibly adaptable to the situation"
}
